### ISSUE TITLE
question

### ISSUE THREAD

**Issue by guoqian0097282** [mnicnc404/CartoonGan-tensorflow#11] opened 2019-05-16 08:21 UTC
when I use inference_with_ckpt.py . 
 I got [ERROR] Failed to load specified weight.
why?

**Comment by guoqian0097282** [comment] 2019-05-16 09:19
when I use inference_with_ckpt.py .
I got [ERROR] Failed to load specified weight.
why?

**Comment by mnicnc404** [comment] 2019-05-17 00:55
> when I use inference_with_ckpt.py .
> I got [ERROR] Failed to load specified weight.
> why?

Can you kindly provide:
1. The command you tried
2. Your environment (OS, python version, TF version, and anything related you can think of)
3. The error message
so we can help you resolve your problem?

**Comment by guoqian0097282** [comment] 2019-05-17 02:12
python:3.7.3   tensorflow:'2.0.0-dev20190516'  I can training. After that I got models include checkpoint generator.data-00000-of-00001  generator.index. Then use “python inference_with_ckpt.py \
    --m_path models \
    --img_path 11.png \
    --out_dir ./1111 \
    --light”    
I got [ERROR] Failed to load specified weight.
[2019-05-16 19:05:52] [inference] [ERROR] If you trained your model with --light, consider adding --light when executing this script; otherwise, do not add --light when executing this script.

**Comment by guoqian0097282** [comment] 2019-05-17 02:14
conda -V :conda 4.6.14

**Comment by guoqian0097282** [comment] 2019-05-17 02:18
when I play around the ckpts with inference_with_ckpt.py and export.py with light_paprika_ckpt and light_shinkai_ckpt,I got the same error.Why?

**Comment by guoqian0097282** [comment] 2019-05-17 09:16
I change python version to 3.6.0 。I got the same error [ERROR] Failed to load specified weight. Can you tell me the reason?

**Comment by mnicnc404** [comment] 2019-05-17 09:27
Thank you for reporting. I think the problem is that our script only accepts RGB image. When it comes to RGBA image, TF engine raises `ValueError` since the model does not accept RGBA (4-channel) image.

We fixed this issue in [12500080](https://github.com/mnicnc404/CartoonGan-tensorflow/commit/12500080ffeaf945a914e41aefc596988d8f053a).

Thank you again for letting us know!

> when I play around the ckpts with inference_with_ckpt.py and export.py with light_paprika_ckpt and light_shinkai_ckpt,I got the same error.Why?

As for `export.py`, can you kindly pull the latest master branch and provide the command and the error message so we can know how to resolve the problem?

**Comment by guoqian0097282** [comment] 2019-05-17 09:33
So do I need to use RGB images when I train?

**Comment by guoqian0097282** [comment] 2019-05-17 09:39
when I run export.py ,I got the error "TypeError: 'NoneType' object is not callable
"

**Comment by mnicnc404** [comment] 2019-05-17 09:42
> So do I need to use RGB images when I train?

Either RGB (e.g., jpg) or RGBA (e.g., png) is OK when it comes to `train.py`. See `train.py` L202:

`x = tf.image.decode_jpeg(x, channels=3)`

According to doc, `tf.image.decode_jpg` supports jpg, png, and non-animated gif. The `channels=3` infers that this function call returns a tensor which has only 3 channels.

**Comment by mnicnc404** [comment] 2019-05-17 09:46
> when I run export.py ,I got the error "TypeError: 'NoneType' object is not callable
> "

Can you provide the full stack trace?

**Comment by guoqian0097282** [comment] 2019-05-17 10:00
I use "python3 export.py     --m_path ./light_shinkai_ckpt    --out_dir ./1111     --light"
Then I got 
 [export] [INFO] tensorflowjs_converter --input_format tf_saved_model --output_format tfjs_graph_model ./1111/SavedModelLight_0018 ./1111/tfjs_model_light_0018
Writing weight file ./1111/tfjs_model_light_0018/model.json...
Exception ignored in: <bound method _EagerDefinedFunctionDeleter.__del__ of <tensorflow.python.eager.function._EagerDefinedFunctionDeleter object at 0x7f471a2da9b0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 305, in __del__
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/eager/context.py", line 1639, in remove_function
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/eager/context.py", line 863, in remove_function
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method _EagerDefinedFunctionDeleter.__del__ of <tensorflow.python.eager.function._EagerDefinedFunctionDeleter object at 0x7f47196d1d68>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 305, in __del__
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/eager/context.py", line 1639, in remove_function
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/eager/context.py", line 863, in remove_function
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method _EagerDefinedFunctionDeleter.__del__ of <tensorflow.python.eager.function._EagerDefinedFunctionDeleter object at 0x7f471868a358>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 305, in __del__
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/eager/context.py", line 1639, in remove_function
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/eager/context.py", line 863, in remove_function
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method _EagerDefinedFunctionDeleter.__del__ of <tensorflow.python.eager.function._EagerDefinedFunctionDeleter object at 0x7f47186292e8>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 305, in __del__
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/eager/context.py", line 1639, in remove_function
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/eager/context.py", line 863, in remove_function
TypeError: 'NoneType' object is not callable

**Comment by mnicnc404** [comment] 2019-05-17 10:44
> tensorflowjs_converter

This problem is caused by `tensorflowjs_converter`, referring to [https://github.com/tensorflow/tfjs/issues/1582](https://github.com/tensorflow/tfjs/issues/1582):

> This model is saved with TF2.0 alpha, but loaded with 2.0 nightly, there could be some mismatch there.

Currently we could not solve this issue since we are not tfjs developers, but can you use the environment we provided by executing the following command:

```
# assuming you're using conda
# make sure you're in CartoonGan-tensorflow
conda env create -n cartoongan -f environment_cpu.yml . # or environment_gpu.yml if you have gpu instance(s)
```

And run `export.py` again? I think it shall resolve the issue.

**Comment by mnicnc404** [comment] 2019-05-18 03:17
I'm closing this issue since we are not tfjs developers and thus cannot fix the tfjs version mismatch problem.

**Closed by mnicnc404** 2019-05-18 03:17 UTC
Labels: bug
