### ISSUE TITLE
Problem with environment_cpu.yml 

### ISSUE THREAD

**Issue by changbaishan** [mnicnc404/CartoonGan-tensorflow#14] opened 2019-05-31 23:41 UTC
Gan-tensorflow$ conda env create -f environment_cpu.yml 
Collecting package metadata: done
Solving environment: done

Downloading and Extracting Packages
openssl-1.1.1c       | 3.8 MB    | ############################# | 100% 
cryptography-2.6.1   | 609 KB    | ############################# | 100% 
python-3.6.8         | 34.4 MB   | ############################# | 100% 
urllib3-1.24.2       | 153 KB    | ############################# | 100% 
sqlite-3.28.0        | 1.9 MB    | ############################# | 100% 
libpng-1.6.37        | 364 KB    | ############################# | 100% 
asn1crypto-0.24.0    | 155 KB    | ############################# | 100% 
imageio-2.5.0        | 3.3 MB    | ############################# | 100% 
setuptools-41.0.1    | 656 KB    | ############################# | 100% 
mkl_random-1.0.1     | 373 KB    | ############################# | 100% 
idna-2.8             | 133 KB    | ############################# | 100% 
mkl_fft-1.0.6        | 150 KB    | ############################# | 100% 
certifi-2019.3.9     | 155 KB    | ############################# | 100% 
olefile-0.46         | 48 KB     | ############################# | 100% 
pip-19.1             | 1.9 MB    | ############################# | 100% 
pycparser-2.19       | 174 KB    | ############################# | 100% 
conda-4.6.14         | 2.1 MB    | ############################# | 100% 
requests-2.21.0      | 85 KB     | ############################# | 100% 
libtiff-4.0.10       | 604 KB    | ############################# | 100% 
chardet-3.0.4        | 189 KB    | ############################# | 100% 
pysocks-1.6.8        | 22 KB     | ############################# | 100% 
libedit-3.1.20181209 | 188 KB    | ############################# | 100% 
wheel-0.33.1         | 39 KB     | ############################# | 100% 
numpy-base-1.15.4    | 4.2 MB    | ############################# | 100% 
mkl-2018.0.3         | 198.7 MB  | ############################# | 100% 
pycosat-0.6.3        | 104 KB    | ############################# | 100% 
pillow-6.0.0         | 626 KB    | ############################# | 100% 
tqdm-4.31.1          | 69 KB     | ############################# | 100% 
pyopenssl-19.0.0     | 82 KB     | ############################# | 100% 
cffi-1.12.3          | 222 KB    | ############################# | 100% 
numpy-1.15.4         | 35 KB     | ############################# | 100% 
ruamel_yaml-0.15.46  | 245 KB    | ############################# | 100% 
six-1.11.0           | 21 KB     | ############################# | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Ran pip subprocess with arguments:
['/home/anaconda3/envs/conda_req/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/Documents/sandbox/playground/test6/CartoonGan-tensorflow/condaenv.4qkm_2s1.requirements.txt']
Pip subprocess output:

Pip subprocess error:
ERROR: Invalid requirement: 'libgfortran=3.0.1=h93005f0_2'
= is not a valid operator. Did you mean == ?

CondaEnvException: Pip failed

**Comment by mnicnc404** [comment] 2019-06-01 05:35
Can you kindly provide your conda version, pip version, and OS?

**Comment by changbaishan** [comment] 2019-06-02 01:13
Hi, thank you very much for the response!
conda 4.6.14
pip 18.1 from /home/comp/anaconda3/lib/python3.7/site-packages/pip (python 3.7)
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

Please help so I can proceed forward, I like your software.

**Comment by mnicnc404** [comment] 2019-06-03 01:37
Sorry, I cannot reproduce the error. Can you try installing all the dependencies manually?

```
conda create -n cartoongan conda python=3.6 numpy mkl imageio pillow tqdm
# skip mkl if you're not using intel CPU
pip install tensorflow==2.0.0a tf-nightly-2.0-preview tensorflowjs
```

**Comment by mnicnc404** [comment] 2019-06-10 00:56
I have updated our yaml file. Please try the following command:
```
conda env create -f environment_linux_cpu.yml
```

**Comment by changbaishan** [comment] 2019-06-10 02:40
Thank you very much for your recent release!

conda env create -n cartoongan -f environment_linux_cpu.yml works out great.

However, when I test with 

python cartoonize.py --input_dir input_images  --output_dir output_images --styles shinkai hayao --comparison_view horizontal
Traceback (most recent call last):
  File "cartoonize.py", line 11, in <module>
    from style_transfer.cartoongan import cartoongan
  File "/home/myself/Documents/sandbox/playground/testtwo/CartoonGan-tensorflow/style_transfer/cartoongan/cartoongan.py", line 4, in <module>
    from keras_contrib.layers import InstanceNormalization
ModuleNotFoundError: No module named 'keras_contrib'

May be you need to include that and possible others in the environment_linux_cpu.yml

Thanks very much,  I value your efforts.

**Comment by leemengtaiwan** [comment] 2019-06-10 02:58
@changbaishan yap it would be better if we include `keras_contrib` in the env file as well, but right now the easiest way to install `keras_contrib` is by running following command:

```bash
git clone https://www.github.com/keras-team/keras-contrib.git \
    && cd keras-contrib \
    && python convert_to_tf_keras.py \
    && USE_TF_KERAS=1 python setup.py install
```

after installing `keras_contrib` you should be able to run the script.

**Comment by mnicnc404** [comment] 2019-06-10 03:21
Currently keras_contrib does not officially offer tf.keras prebuilt package, so unfortunately we can not include this package into our environment yamls.

Closing the issue since the original problem is solved. Feel free to reopen it if you encounter any other related problems.

**Closed by mnicnc404** 2019-06-10 03:21 UTC
